
maps = {
    'First Name': 'first_name',
    'Last Name': 'last_name',
    '出生年': 'birth_year',
    '出生月': 'birth_month',
    '出生日': 'birth_day',
    '生日': 'birthday',
    'SSN': 'ssn',
    'SSN后四位': 'ssn_last4',
    '邮箱': 'email',
    '家庭电话': 'home_phone',
    '工作电话': 'work_phone',
    '地址': 'address',
    '城市': 'city',
    '州/省': 'state',
    '邮编': 'zip_code',
    '雇主': 'employer',
    '岗位': 'job_title',
    '工作年限': 'years_employed',
    '驾照': 'driver_license',
    '驾照州': 'driver_license_state',
    'Card Type': 'card_type',
    'Routing Number': 'card_routing_number',
    'Account Number': 'card_account_number',
    'Bank Name': 'bank_name',
    '居住类型': 'resident_type',
    '居住年限': 'years_resident',
    '联系时间': 'contact_time',
    '收入类型': 'income_type',
    '支付周期': 'pay_frequency',
    '月收入': 'monthly_income',
    '年收入': 'year_income'
}
