
maps = {
    'First Name': 'first_name',
    'Last Name': 'last_name',
    'Birth Year': 'birth_year',
    'Birthday': 'birthday',
    'SSN': 'ssn',
    'SSN Last4': 'ssn_last4',
    'Email': 'email',
    'Home Phone': 'home_phone',
    'Work Phone': 'work_phone',
    'Address': 'address',
    'City': 'city',
    'State': 'state',
    'Zip Code': 'zip_code',
    'Employer': 'employer',
    'Job Title': 'job_title',
    'Work Year': 'years_employed',
    'Driver License': 'driver_license',
    'Driver License State': 'driver_license_state',
    'Card Type': 'card_type',
    'Routing Number': 'card_routing_number',
    'Account Number': 'card_account_number',
    'Bank Name': 'bank_name',
    'Resident Type': 'resident_type',
    'Years Resident': 'years_resident',
    'Contact Time': 'contact_time',
    'Income Type': 'income_type',
    'Pay Frequency': 'pay_frequency',
    'Monthly Income': 'monthly_income',
    'Year Income': 'year_income'
}
