# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TaskCell.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget


class TaskCell(QWidget):
    
    
    def setupUi(self):
        verticalLayout_2 = QtWidgets.QVBoxLayout()

        verticalLayout = QtWidgets.QVBoxLayout()

        horizontalLayout = QtWidgets.QHBoxLayout()

        label = QtWidgets.QLabel("任务名称")
        horizontalLayout.addWidget(label)
        
        label_2 = QtWidgets.QLabel("创建时间：2021-09-20")
        label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        horizontalLayout.addWidget(label_2)
        
        verticalLayout.addLayout(horizontalLayout)
        verticalLayout_2.addLayout(verticalLayout)
        
        horizontalLayout_7 = QtWidgets.QHBoxLayout()

        label_4 = QtWidgets.QLabel("累计成功/累计完成")
        horizontalLayout_7.addWidget(label_4)
        
        label_6 = QtWidgets.QLabel("0/0")
        label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        horizontalLayout_7.addWidget(label_6)
        
        verticalLayout_2.addLayout(horizontalLayout_7)
        horizontalLayout_9 = QtWidgets.QHBoxLayout()

        label_3 = QtWidgets.QLabel("今日成功/今日完成")
        horizontalLayout_9.addWidget(label_3)
        
        label_5 = QtWidgets.QLabel("0/0")
        label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)

        horizontalLayout_9.addWidget(label_5)
        verticalLayout_2.addLayout(horizontalLayout_9)
        horizontalLayout_4 = QtWidgets.QHBoxLayout()

        label_9 = QtWidgets.QLabel("代理IP")
        horizontalLayout_4.addWidget(label_9)
        
        label_8 = QtWidgets.QLabel("端口")
        label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        horizontalLayout_4.addWidget(label_8)
        
        verticalLayout_2.addLayout(horizontalLayout_4)
        label_10 = QtWidgets.QLabel("配置文件ID")
        verticalLayout_2.addWidget(label_10)
        
        label_7 = QtWidgets.QLabel("任务链接地址")
        verticalLayout_2.addWidget(label_7)
        
        toolButton = QtWidgets.QToolButton()
        toolButton.setText("开启")

        toolButton.setMinimumSize(QtCore.QSize(100, 40))
        toolButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        toolButton.setAutoFillBackground(False)

        verticalLayout_2.addWidget(toolButton)

        self.setLayout(verticalLayout_2)


